import { expect, type Page, test } from '@playwright/test';

type BrowserIssue = {
  kind: 'console' | 'page';
  message: string;
};

function collectBrowserIssues(page: Page): BrowserIssue[] {
  const issues: BrowserIssue[] = [];

  page.on('pageerror', (error) => {
    issues.push({ kind: 'page', message: error.message });
  });
  page.on('console', (message) => {
    if (message.type() === 'error') {
      const location = message.location().url;
      issues.push({
        kind: 'console',
        message: location ? `${message.text()} [${location}]` : message.text(),
      });
    }
  });

  return issues;
}

async function waitForMap(page: Page): Promise<void> {
  await page.waitForSelector('canvas.maplibregl-canvas', { timeout: 30_000 });
  await page.waitForFunction(() => {
    const registry = (
      window as typeof window & {
        __dioxus_maplibre_maps?: Record<string, object>;
      }
    ).__dioxus_maplibre_maps;
    const maps = registry ? [...new Set(Object.values(registry))] : [];
    return maps.length > 0;
  }, undefined, { timeout: 30_000 });
}

async function openMapRoute(page: Page, path: string): Promise<BrowserIssue[]> {
  const issues = collectBrowserIssues(page);
  await page.goto(path);
  await waitForMap(page);
  return issues;
}

async function expectNoBrowserIssues(page: Page, issues: BrowserIssue[]): Promise<void> {
  await page.waitForTimeout(1_000);
  expect(issues).toEqual([]);
}

const mapRoutes = [
  '/',
  '/declarative',
  '/markers',
  '/sources',
  '/media-sources',
  '/layers',
  '/raster-relief',
  '/controls',
  '/navigation',
  '/camera-state',
  '/interaction',
  '/lifecycle',
  '/terrain',
  '/style',
  '/expressions',
  '/eval',
  '/heatmap',
  '/symbols',
  '/popups',
  '/buildings',
  '/patterns',
  '/query',
  '/animation',
  '/fog',
  '/projections',
  '/stress',
] as const;

test.describe('complete showcase route sweep', () => {
  test.describe.configure({ mode: 'parallel' });

  for (const path of mapRoutes) {
    test(`${path} renders a loaded map without browser errors`, async ({ page }) => {
      const issues = await openMapRoute(page, path);
      await expect(page.locator('canvas.maplibregl-canvas')).toBeVisible();
      await page.waitForTimeout(1_000);
      expect(issues, `browser issues on ${path}`).toEqual([]);
    });
  }

  test('coverage reports every core area', async ({ page }) => {
    await page.goto('/coverage');
    await expect(page.getByTestId('coverage-status')).toHaveText(
      '17 / 17 core feature areas represented in the showcase',
    );
  });
});

test.describe('MapLibre 6 feature examples', () => {
  test.describe.configure({ mode: 'parallel' });

  test('declarative children mount sources, layers, markers, popups, and controls', async ({ page }) => {
    const issues = await openMapRoute(page, '/declarative');

    await expect(page.getByTestId('declarative-status')).toContainText('All declarative');
    await expect(page.locator('.maplibregl-marker')).toBeVisible();
    await expect(page.locator('.maplibregl-popup')).toContainText('Declarative popup');
    await expect(page.locator('.maplibregl-ctrl-zoom-in')).toBeVisible();
    await expect.poll(async () => page.evaluate(() => {
      const maps = Object.values((window as any).__dioxus_maplibre_maps ?? {}) as any[];
      const map = maps[0];
      return Boolean(map?.getSource('declarative-source') && map?.getLayer('declarative-layer'));
    })).toBe(true);
    await expectNoBrowserIssues(page, issues);
  });

  test('missing-style-image resolver generates the pattern', async ({ page }) => {
    const issues = await openMapRoute(page, '/patterns');
    await expect(page.getByTestId('pattern-status')).toContainText(
      'Generated by v6 resolver',
      { timeout: 10_000 },
    );
    await expectNoBrowserIssues(page, issues);
  });

  test('raster, hillshade, and color-relief modes can be selected', async ({ page }) => {
    const issues = await openMapRoute(page, '/raster-relief');

    await page.getByTestId('show-hillshade').click();
    await expect(page.getByTestId('raster-mode')).toHaveText('Mode: hillshade');
    await page.getByTestId('show-raster').click();
    await expect(page.getByTestId('raster-mode')).toHaveText('Mode: raster');
    await page.getByTestId('show-relief').click();
    await expect(page.getByTestId('raster-mode')).toHaveText('Mode: color-relief');
    await expectNoBrowserIssues(page, issues);
  });

  test('canvas, image, and video sources register and video controls work', async ({ page }) => {
    const issues = await openMapRoute(page, '/media-sources');

    await expect(page.getByTestId('media-status')).toHaveText(
      'canvas + image + video registered',
      { timeout: 10_000 },
    );
    await expect.poll(async () => page.evaluate(() => {
      const maps = Object.values((window as any).__dioxus_maplibre_maps ?? {}) as any[];
      const map = maps[0];
      return ['canvas-media', 'image-media', 'video-media'].every((id) => Boolean(map?.getSource(id)));
    })).toBe(true);
    await page.getByTestId('toggle-video').click();
    await expect(page.getByTestId('toggle-video')).toHaveText('Play video');
    await expectNoBrowserIssues(page, issues);
  });

  test('camera state exposes projections, constraints, interactions, and coordinate conversion', async ({ page }) => {
    const issues = await openMapRoute(page, '/camera-state');

    await page.getByTestId('project-coordinate').click();
    await expect(page.getByTestId('camera-readout')).toContainText('project →', { timeout: 5_000 });
    await expect(page.getByTestId('camera-readout')).toContainText('unproject → Some');
    await page.getByTestId('toggle-drag-pan').click();
    await expect(page.getByTestId('toggle-drag-pan')).toHaveText('Enable pan + wheel');
    await page.getByTestId('toggle-world-copies').click();
    await expect(page.getByTestId('toggle-world-copies')).toHaveText('Enable world copies');
    await expectNoBrowserIssues(page, issues);
  });

  test('nested properties and global state drive expressions', async ({ page }) => {
    const issues = await openMapRoute(page, '/expressions');

    await page.getByRole('button', { name: 'rail', exact: true }).click();
    await expect(page.getByTestId('global-state-value')).toHaveText('Category: rail');
    await expect.poll(async () => page.evaluate(() => {
      const maps = Object.values((window as any).__dioxus_maplibre_maps ?? {}) as any[];
      return maps[0]?.getGlobalState?.()?.category;
    })).toBe('rail');
    await expectNoBrowserIssues(page, issues);
  });

  test('lifecycle and camera event classes reach Dioxus callbacks', async ({ page }) => {
    const issues = await openMapRoute(page, '/lifecycle');

    await expect(page.getByTestId('lifecycle-log')).toContainText('load / ready');
    await page.getByTestId('emit-camera-events').click();
    await expect(page.getByTestId('lifecycle-log')).toContainText(/(rollend|rotateend|pitchend|zoomend)/, {
      timeout: 10_000,
    });
    await expectNoBrowserIssues(page, issues);
  });

  test('sky/fog compatibility uses the current setSky API', async ({ page }) => {
    const issues = await openMapRoute(page, '/fog');

    await expect.poll(async () => page.evaluate(() => {
      const maps = Object.values((window as any).__dioxus_maplibre_maps ?? {}) as any[];
      const map = maps[0];
      return {
        hasSky: Boolean(map?.getSky?.()),
        legacyMethod: typeof map?.setFog,
      };
    })).toEqual({ hasSky: true, legacyMethod: 'undefined' });
    await page.getByTestId('preset-night').click();
    await expect(page.getByTestId('fog-preset')).toHaveText('Preset: night');
    await page.getByTestId('toggle-fog').click();
    await expect(page.getByTestId('toggle-fog')).toHaveText('Enable Fog');
    await expectNoBrowserIssues(page, issues);
  });

  test('globe, Mercator, vertical perspective, and roll switch at runtime', async ({ page }) => {
    const issues = await openMapRoute(page, '/projections');

    await page.getByTestId('projection-mercator').click();
    await expect(page.getByTestId('projection-status')).toHaveText('Projection: mercator');
    await expect.poll(async () => page.evaluate(() => {
      const maps = Object.values((window as any).__dioxus_maplibre_maps ?? {}) as any[];
      return maps[0]?.getProjection?.().type;
    })).toBe('mercator');

    await page.getByTestId('projection-perspective').click();
    await expect(page.getByTestId('projection-status')).toHaveText('Projection: vertical-perspective');
    await page.getByTestId('roll-camera').click();
    await expect(page.getByTestId('roll-value')).toHaveText('Roll: 20.0°', { timeout: 10_000 });
    await expectNoBrowserIssues(page, issues);
  });

  test('all eight built-in control categories render', async ({ page }) => {
    const issues = await openMapRoute(page, '/controls');

    for (const selector of [
      '.maplibregl-ctrl-zoom-in',
      '.maplibregl-ctrl-scale',
      '.maplibregl-ctrl-fullscreen',
      '.maplibregl-ctrl-geolocate',
      '.maplibregl-ctrl-attrib',
      '.maplibregl-ctrl-globe',
      '.maplibregl-ctrl-logo',
      '.maplibregl-ctrl-terrain',
    ]) {
      await expect(page.locator(selector).first(), selector).toBeVisible();
    }
    await expectNoBrowserIssues(page, issues);
  });

  test('terrain control and typed terrain state work', async ({ page }) => {
    const issues = await openMapRoute(page, '/terrain');

    await expect(page.locator('.maplibregl-ctrl-terrain')).toBeVisible();
    await page.getByTestId('toggle-terrain').click();
    await expect(page.getByTestId('toggle-terrain')).toHaveText('Disable Terrain');
    await expect.poll(async () => page.evaluate(() => {
      const maps = Object.values((window as any).__dioxus_maplibre_maps ?? {}) as any[];
      return maps[0]?.getTerrain?.()?.source;
    })).toBe('terrain-dem');
    await expectNoBrowserIssues(page, issues);
  });
});
