[application]
name = "dioxus-maplibre showcase"

[web.app]
title = "dioxus-maplibre showcase"

[web.resource]
style = ["https://unpkg.com/maplibre-gl@6.0.0/dist/maplibre-gl.css"]
script = ["/maplibre-loader.js"]

[web.resource.dev]
