use dioxus::prelude::*;
use dioxus_maplibre::{
    GeoJsonSourceOptions, LatLng, LayerOptions, Map, MapHandle, MissingImageOptions,
};
use gloo_timers::future::TimeoutFuture;
use serde_json::json;

#[component]
pub fn Patterns() -> Element {
    let mut map_handle = use_signal(|| None::<MapHandle>);
    let mut status = use_signal(|| "Loading...".to_string());
    let style: Signal<String> = use_context();

    rsx! {
        div { style: "display: flex; height: 100%;",
            div { style: "flex: 1; position: relative;",
                Map {
                    style: style(),
                    center: LatLng::new(60.17, 24.94),
                    zoom: 13.0,
                    on_ready: move |handle: MapHandle| {
                        map_handle.set(Some(handle.clone()));

                        handle.set_missing_image_resolver(MissingImageOptions {
                            width: 32,
                            height: 32,
                            cell_size: 8,
                            primary_color: "#2563eb".into(),
                            secondary_color: "#dbeafe".into(),
                            pixel_ratio: Some(2.0),
                        });

                        // The layer intentionally references a missing image. MapLibre 6 asks
                        // the resolver to generate it before styleimagemissing is emitted.
                        handle.add_geojson_source("pattern-area", GeoJsonSourceOptions {
                                    data: json!({
                                        "type": "FeatureCollection",
                                        "features": [
                                            {
                                                "type": "Feature",
                                                "geometry": {
                                                    "type": "Polygon",
                                                    "coordinates": [[
                                                        [24.92, 60.165], [24.96, 60.165],
                                                        [24.96, 60.175], [24.92, 60.175],
                                                        [24.92, 60.165]
                                                    ]]
                                                }
                                            },
                                            {
                                                "type": "Feature",
                                                "geometry": {
                                                    "type": "Polygon",
                                                    "coordinates": [[
                                                        [24.93, 60.176], [24.95, 60.176],
                                                        [24.95, 60.182], [24.93, 60.182],
                                                        [24.93, 60.176]
                                                    ]]
                                                }
                                            }
                                        ]
                                    }),
                                    ..Default::default()
                        });

                        handle.add_layer(LayerOptions::fill("pattern-fill", "pattern-area")
                                    .paint(json!({
                                        "fill-pattern": "stripe-pattern",
                                        "fill-opacity": 0.8
                                    }))
                        );

                        handle.add_layer(LayerOptions::line("pattern-outline", "pattern-area")
                                    .paint(json!({
                                        "line-color": "#3b82f6",
                                        "line-width": 2
                                    }))
                        );

                        spawn(async move {
                            TimeoutFuture::new(400).await;
                            if handle.has_image("stripe-pattern").await {
                                status.set("Generated by v6 resolver".to_string());
                            } else {
                                status.set("Resolver pending".to_string());
                            }
                        });
                    },
                }
            }
            div { style: "width: 280px; background: #16213e; color: #e0e0e0; padding: 16px; font-size: 13px;",
                h3 { style: "margin: 0 0 12px 0;", "Patterns (Image Fills)" }
                p { "Fill pattern generated locally with MapLibre 6's missing-style-image resolver." }
                p {
                    "data-testid": "pattern-status",
                    style: "margin-top: 8px;",
                    "Status: {status}"
                }
            }
        }
    }
}
